// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AlertRuleMode.
const (
	AlertRuleModeAdvisory AlertRuleMode = "advisory"
	AlertRuleModeBlocking AlertRuleMode = "blocking"
)

// Valid indicates whether the value is a known member of the AlertRuleMode enum.
func (e AlertRuleMode) Valid() bool {
	switch e {
	case AlertRuleModeAdvisory:
		return true
	case AlertRuleModeBlocking:
		return true
	default:
		return false
	}
}

// Defines values for AlertRuleInputMode.
const (
	AlertRuleInputModeAdvisory AlertRuleInputMode = "advisory"
	AlertRuleInputModeBlocking AlertRuleInputMode = "blocking"
)

// Valid indicates whether the value is a known member of the AlertRuleInputMode enum.
func (e AlertRuleInputMode) Valid() bool {
	switch e {
	case AlertRuleInputModeAdvisory:
		return true
	case AlertRuleInputModeBlocking:
		return true
	default:
		return false
	}
}

// Defines values for AllowedAction.
const (
	AllowedActionAcknowledge AllowedAction = "acknowledge"
	AllowedActionApprove     AllowedAction = "approve"
	AllowedActionDelegate    AllowedAction = "delegate"
	AllowedActionOpen        AllowedAction = "open"
	AllowedActionReject      AllowedAction = "reject"
	AllowedActionSnooze      AllowedAction = "snooze"
)

// Valid indicates whether the value is a known member of the AllowedAction enum.
func (e AllowedAction) Valid() bool {
	switch e {
	case AllowedActionAcknowledge:
		return true
	case AllowedActionApprove:
		return true
	case AllowedActionDelegate:
		return true
	case AllowedActionOpen:
		return true
	case AllowedActionReject:
		return true
	case AllowedActionSnooze:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalDetailDecisionsDecision.
const (
	ApprovalDetailDecisionsDecisionApproved  ApprovalDetailDecisionsDecision = "approved"
	ApprovalDetailDecisionsDecisionDelegated ApprovalDetailDecisionsDecision = "delegated"
	ApprovalDetailDecisionsDecisionRejected  ApprovalDetailDecisionsDecision = "rejected"
)

// Valid indicates whether the value is a known member of the ApprovalDetailDecisionsDecision enum.
func (e ApprovalDetailDecisionsDecision) Valid() bool {
	switch e {
	case ApprovalDetailDecisionsDecisionApproved:
		return true
	case ApprovalDetailDecisionsDecisionDelegated:
		return true
	case ApprovalDetailDecisionsDecisionRejected:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalMatrixRuleStatus.
const (
	ApprovalMatrixRuleStatusActive          ApprovalMatrixRuleStatus = "active"
	ApprovalMatrixRuleStatusPendingApproval ApprovalMatrixRuleStatus = "pending_approval"
)

// Valid indicates whether the value is a known member of the ApprovalMatrixRuleStatus enum.
func (e ApprovalMatrixRuleStatus) Valid() bool {
	switch e {
	case ApprovalMatrixRuleStatusActive:
		return true
	case ApprovalMatrixRuleStatusPendingApproval:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalState.
const (
	ApprovalStateApproved  ApprovalState = "approved"
	ApprovalStateCancelled ApprovalState = "cancelled"
	ApprovalStateDelegated ApprovalState = "delegated"
	ApprovalStatePending   ApprovalState = "pending"
	ApprovalStatePosted    ApprovalState = "posted"
	ApprovalStateRejected  ApprovalState = "rejected"
	ApprovalStateSnoozed   ApprovalState = "snoozed"
)

// Valid indicates whether the value is a known member of the ApprovalState enum.
func (e ApprovalState) Valid() bool {
	switch e {
	case ApprovalStateApproved:
		return true
	case ApprovalStateCancelled:
		return true
	case ApprovalStateDelegated:
		return true
	case ApprovalStatePending:
		return true
	case ApprovalStatePosted:
		return true
	case ApprovalStateRejected:
		return true
	case ApprovalStateSnoozed:
		return true
	default:
		return false
	}
}

// Defines values for DecisionMetaNotice.
const (
	DecisionMetaNoticeALREADYDECIDED DecisionMetaNotice = "ALREADY_DECIDED"
)

// Valid indicates whether the value is a known member of the DecisionMetaNotice enum.
func (e DecisionMetaNotice) Valid() bool {
	switch e {
	case DecisionMetaNoticeALREADYDECIDED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeALREADYDECIDED   ErrorCode = "ALREADY_DECIDED"
	ErrorCodeAUTHREQUIRED     ErrorCode = "AUTH_REQUIRED"
	ErrorCodeCONFLICT         ErrorCode = "CONFLICT"
	ErrorCodeCREDITHOLD       ErrorCode = "CREDIT_HOLD"
	ErrorCodeDEVICEMISMATCH   ErrorCode = "DEVICE_MISMATCH"
	ErrorCodeIMMUTABLE        ErrorCode = "IMMUTABLE"
	ErrorCodeINTERNALERROR    ErrorCode = "INTERNAL_ERROR"
	ErrorCodeMISSINGCONFIG    ErrorCode = "MISSING_CONFIG"
	ErrorCodeNEGATIVESTOCK    ErrorCode = "NEGATIVE_STOCK"
	ErrorCodeNOTFOUND         ErrorCode = "NOT_FOUND"
	ErrorCodePERIODCLOSED     ErrorCode = "PERIOD_CLOSED"
	ErrorCodePERMISSIONDENIED ErrorCode = "PERMISSION_DENIED"
	ErrorCodePRICEFLOORHOLD   ErrorCode = "PRICE_FLOOR_HOLD"
	ErrorCodeRATELIMITED      ErrorCode = "RATE_LIMITED"
	ErrorCodeSODVIOLATION     ErrorCode = "SOD_VIOLATION"
	ErrorCodeSTEPUPREQUIRED   ErrorCode = "STEP_UP_REQUIRED"
	ErrorCodeTOKENEXPIRED     ErrorCode = "TOKEN_EXPIRED"
	ErrorCodeTOKENREVOKED     ErrorCode = "TOKEN_REVOKED"
	ErrorCodeVALIDATIONERROR  ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeALREADYDECIDED:
		return true
	case ErrorCodeAUTHREQUIRED:
		return true
	case ErrorCodeCONFLICT:
		return true
	case ErrorCodeCREDITHOLD:
		return true
	case ErrorCodeDEVICEMISMATCH:
		return true
	case ErrorCodeIMMUTABLE:
		return true
	case ErrorCodeINTERNALERROR:
		return true
	case ErrorCodeMISSINGCONFIG:
		return true
	case ErrorCodeNEGATIVESTOCK:
		return true
	case ErrorCodeNOTFOUND:
		return true
	case ErrorCodePERIODCLOSED:
		return true
	case ErrorCodePERMISSIONDENIED:
		return true
	case ErrorCodePRICEFLOORHOLD:
		return true
	case ErrorCodeRATELIMITED:
		return true
	case ErrorCodeSODVIOLATION:
		return true
	case ErrorCodeSTEPUPREQUIRED:
		return true
	case ErrorCodeTOKENEXPIRED:
		return true
	case ErrorCodeTOKENREVOKED:
		return true
	case ErrorCodeVALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded    HealthResponseStatus = "degraded"
	HealthResponseStatusOk          HealthResponseStatus = "ok"
	HealthResponseStatusUnavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	case HealthResponseStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for NotificationPreferencesChannelsChannel.
const (
	Digest    NotificationPreferencesChannelsChannel = "digest"
	Email     NotificationPreferencesChannelsChannel = "email"
	Push      NotificationPreferencesChannelsChannel = "push"
	Websocket NotificationPreferencesChannelsChannel = "websocket"
)

// Valid indicates whether the value is a known member of the NotificationPreferencesChannelsChannel enum.
func (e NotificationPreferencesChannelsChannel) Valid() bool {
	switch e {
	case Digest:
		return true
	case Email:
		return true
	case Push:
		return true
	case Websocket:
		return true
	default:
		return false
	}
}

// Defines values for PeriodKind.
const (
	AuditAdjustment PeriodKind = "audit_adjustment"
	Month           PeriodKind = "month"
)

// Valid indicates whether the value is a known member of the PeriodKind enum.
func (e PeriodKind) Valid() bool {
	switch e {
	case AuditAdjustment:
		return true
	case Month:
		return true
	default:
		return false
	}
}

// Defines values for PeriodStatus.
const (
	PeriodStatusHardClosed PeriodStatus = "hard_closed"
	PeriodStatusOpen       PeriodStatus = "open"
	PeriodStatusSoftClosed PeriodStatus = "soft_closed"
)

// Valid indicates whether the value is a known member of the PeriodStatus enum.
func (e PeriodStatus) Valid() bool {
	switch e {
	case PeriodStatusHardClosed:
		return true
	case PeriodStatusOpen:
		return true
	case PeriodStatusSoftClosed:
		return true
	default:
		return false
	}
}

// Defines values for Platform.
const (
	Android Platform = "android"
	Console Platform = "console"
	Ios     Platform = "ios"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case Android:
		return true
	case Console:
		return true
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for Severity.
const (
	CRITICAL Severity = "CRITICAL"
	HIGH     Severity = "HIGH"
	LOW      Severity = "LOW"
	MEDIUM   Severity = "MEDIUM"
)

// Valid indicates whether the value is a known member of the Severity enum.
func (e Severity) Valid() bool {
	switch e {
	case CRITICAL:
		return true
	case HIGH:
		return true
	case LOW:
		return true
	case MEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for SodRuleKind.
const (
	SodRuleKindActionPair SodRuleKind = "action_pair"
	SodRuleKindRolePair   SodRuleKind = "role_pair"
)

// Valid indicates whether the value is a known member of the SodRuleKind enum.
func (e SodRuleKind) Valid() bool {
	switch e {
	case SodRuleKindActionPair:
		return true
	case SodRuleKindRolePair:
		return true
	default:
		return false
	}
}

// Defines values for SodRuleStatus.
const (
	SodRuleStatusActive          SodRuleStatus = "active"
	SodRuleStatusPendingApproval SodRuleStatus = "pending_approval"
)

// Valid indicates whether the value is a known member of the SodRuleStatus enum.
func (e SodRuleStatus) Valid() bool {
	switch e {
	case SodRuleStatusActive:
		return true
	case SodRuleStatusPendingApproval:
		return true
	default:
		return false
	}
}

// Defines values for SodRuleWriteKind.
const (
	SodRuleWriteKindActionPair SodRuleWriteKind = "action_pair"
	SodRuleWriteKindRolePair   SodRuleWriteKind = "role_pair"
)

// Valid indicates whether the value is a known member of the SodRuleWriteKind enum.
func (e SodRuleWriteKind) Valid() bool {
	switch e {
	case SodRuleWriteKindActionPair:
		return true
	case SodRuleWriteKindRolePair:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseRecoveryPointInForce.
const (
	N15m StatusResponseRecoveryPointInForce = "15m"
	N24h StatusResponseRecoveryPointInForce = "24h"
)

// Valid indicates whether the value is a known member of the StatusResponseRecoveryPointInForce enum.
func (e StatusResponseRecoveryPointInForce) Valid() bool {
	switch e {
	case N15m:
		return true
	case N24h:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseWorkerHealth.
const (
	StatusResponseWorkerHealthDegraded StatusResponseWorkerHealth = "degraded"
	StatusResponseWorkerHealthDown     StatusResponseWorkerHealth = "down"
	StatusResponseWorkerHealthOk       StatusResponseWorkerHealth = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseWorkerHealth enum.
func (e StatusResponseWorkerHealth) Valid() bool {
	switch e {
	case StatusResponseWorkerHealthDegraded:
		return true
	case StatusResponseWorkerHealthDown:
		return true
	case StatusResponseWorkerHealthOk:
		return true
	default:
		return false
	}
}

// Defines values for StatusRunResult.
const (
	StatusRunResultFailed StatusRunResult = "failed"
	StatusRunResultNever  StatusRunResult = "never"
	StatusRunResultOk     StatusRunResult = "ok"
)

// Valid indicates whether the value is a known member of the StatusRunResult enum.
func (e StatusRunResult) Valid() bool {
	switch e {
	case StatusRunResultFailed:
		return true
	case StatusRunResultNever:
		return true
	case StatusRunResultOk:
		return true
	default:
		return false
	}
}

// Defines values for TokenResponseStepUpMethods.
const (
	TokenResponseStepUpMethodsBiometric TokenResponseStepUpMethods = "biometric"
	TokenResponseStepUpMethodsTotp      TokenResponseStepUpMethods = "totp"
	TokenResponseStepUpMethodsWebauthn  TokenResponseStepUpMethods = "webauthn"
)

// Valid indicates whether the value is a known member of the TokenResponseStepUpMethods enum.
func (e TokenResponseStepUpMethods) Valid() bool {
	switch e {
	case TokenResponseStepUpMethodsBiometric:
		return true
	case TokenResponseStepUpMethodsTotp:
		return true
	case TokenResponseStepUpMethodsWebauthn:
		return true
	default:
		return false
	}
}

// Defines values for Weekday.
const (
	Friday    Weekday = "friday"
	Monday    Weekday = "monday"
	Saturday  Weekday = "saturday"
	Sunday    Weekday = "sunday"
	Thursday  Weekday = "thursday"
	Tuesday   Weekday = "tuesday"
	Wednesday Weekday = "wednesday"
)

// Valid indicates whether the value is a known member of the Weekday enum.
func (e Weekday) Valid() bool {
	switch e {
	case Friday:
		return true
	case Monday:
		return true
	case Saturday:
		return true
	case Sunday:
		return true
	case Thursday:
		return true
	case Tuesday:
		return true
	case Wednesday:
		return true
	default:
		return false
	}
}

// Defines values for AcceptLanguage.
const (
	AcceptLanguageAr AcceptLanguage = "ar"
	AcceptLanguageEn AcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the AcceptLanguage enum.
func (e AcceptLanguage) Valid() bool {
	switch e {
	case AcceptLanguageAr:
		return true
	case AcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListAlertRulesParamsAcceptLanguage.
const (
	ListAlertRulesParamsAcceptLanguageAr ListAlertRulesParamsAcceptLanguage = "ar"
	ListAlertRulesParamsAcceptLanguageEn ListAlertRulesParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListAlertRulesParamsAcceptLanguage enum.
func (e ListAlertRulesParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListAlertRulesParamsAcceptLanguageAr:
		return true
	case ListAlertRulesParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for CreateAlertRuleParamsAcceptLanguage.
const (
	CreateAlertRuleParamsAcceptLanguageAr CreateAlertRuleParamsAcceptLanguage = "ar"
	CreateAlertRuleParamsAcceptLanguageEn CreateAlertRuleParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the CreateAlertRuleParamsAcceptLanguage enum.
func (e CreateAlertRuleParamsAcceptLanguage) Valid() bool {
	switch e {
	case CreateAlertRuleParamsAcceptLanguageAr:
		return true
	case CreateAlertRuleParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListApprovalMatrixParamsAcceptLanguage.
const (
	ListApprovalMatrixParamsAcceptLanguageAr ListApprovalMatrixParamsAcceptLanguage = "ar"
	ListApprovalMatrixParamsAcceptLanguageEn ListApprovalMatrixParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListApprovalMatrixParamsAcceptLanguage enum.
func (e ListApprovalMatrixParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListApprovalMatrixParamsAcceptLanguageAr:
		return true
	case ListApprovalMatrixParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for CreateApprovalMatrixRuleParamsAcceptLanguage.
const (
	CreateApprovalMatrixRuleParamsAcceptLanguageAr CreateApprovalMatrixRuleParamsAcceptLanguage = "ar"
	CreateApprovalMatrixRuleParamsAcceptLanguageEn CreateApprovalMatrixRuleParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the CreateApprovalMatrixRuleParamsAcceptLanguage enum.
func (e CreateApprovalMatrixRuleParamsAcceptLanguage) Valid() bool {
	switch e {
	case CreateApprovalMatrixRuleParamsAcceptLanguageAr:
		return true
	case CreateApprovalMatrixRuleParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListApprovalInboxParamsState.
const (
	ListApprovalInboxParamsStateFyi             ListApprovalInboxParamsState = "fyi"
	ListApprovalInboxParamsStateNeedsMe         ListApprovalInboxParamsState = "needs_me"
	ListApprovalInboxParamsStateWaitingOnOthers ListApprovalInboxParamsState = "waiting_on_others"
)

// Valid indicates whether the value is a known member of the ListApprovalInboxParamsState enum.
func (e ListApprovalInboxParamsState) Valid() bool {
	switch e {
	case ListApprovalInboxParamsStateFyi:
		return true
	case ListApprovalInboxParamsStateNeedsMe:
		return true
	case ListApprovalInboxParamsStateWaitingOnOthers:
		return true
	default:
		return false
	}
}

// Defines values for ListApprovalInboxParamsAcceptLanguage.
const (
	ListApprovalInboxParamsAcceptLanguageAr ListApprovalInboxParamsAcceptLanguage = "ar"
	ListApprovalInboxParamsAcceptLanguageEn ListApprovalInboxParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListApprovalInboxParamsAcceptLanguage enum.
func (e ListApprovalInboxParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListApprovalInboxParamsAcceptLanguageAr:
		return true
	case ListApprovalInboxParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for GetApprovalParamsAcceptLanguage.
const (
	GetApprovalParamsAcceptLanguageAr GetApprovalParamsAcceptLanguage = "ar"
	GetApprovalParamsAcceptLanguageEn GetApprovalParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the GetApprovalParamsAcceptLanguage enum.
func (e GetApprovalParamsAcceptLanguage) Valid() bool {
	switch e {
	case GetApprovalParamsAcceptLanguageAr:
		return true
	case GetApprovalParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ApproveApprovalParamsAcceptLanguage.
const (
	ApproveApprovalParamsAcceptLanguageAr ApproveApprovalParamsAcceptLanguage = "ar"
	ApproveApprovalParamsAcceptLanguageEn ApproveApprovalParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ApproveApprovalParamsAcceptLanguage enum.
func (e ApproveApprovalParamsAcceptLanguage) Valid() bool {
	switch e {
	case ApproveApprovalParamsAcceptLanguageAr:
		return true
	case ApproveApprovalParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for RejectApprovalParamsAcceptLanguage.
const (
	RejectApprovalParamsAcceptLanguageAr RejectApprovalParamsAcceptLanguage = "ar"
	RejectApprovalParamsAcceptLanguageEn RejectApprovalParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the RejectApprovalParamsAcceptLanguage enum.
func (e RejectApprovalParamsAcceptLanguage) Valid() bool {
	switch e {
	case RejectApprovalParamsAcceptLanguageAr:
		return true
	case RejectApprovalParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListAuditEventsParamsAcceptLanguage.
const (
	ListAuditEventsParamsAcceptLanguageAr ListAuditEventsParamsAcceptLanguage = "ar"
	ListAuditEventsParamsAcceptLanguageEn ListAuditEventsParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListAuditEventsParamsAcceptLanguage enum.
func (e ListAuditEventsParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListAuditEventsParamsAcceptLanguageAr:
		return true
	case ListAuditEventsParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for VerifyAuditChainParamsAcceptLanguage.
const (
	VerifyAuditChainParamsAcceptLanguageAr VerifyAuditChainParamsAcceptLanguage = "ar"
	VerifyAuditChainParamsAcceptLanguageEn VerifyAuditChainParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the VerifyAuditChainParamsAcceptLanguage enum.
func (e VerifyAuditChainParamsAcceptLanguage) Valid() bool {
	switch e {
	case VerifyAuditChainParamsAcceptLanguageAr:
		return true
	case VerifyAuditChainParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for EnrollDeviceParamsAcceptLanguage.
const (
	EnrollDeviceParamsAcceptLanguageAr EnrollDeviceParamsAcceptLanguage = "ar"
	EnrollDeviceParamsAcceptLanguageEn EnrollDeviceParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the EnrollDeviceParamsAcceptLanguage enum.
func (e EnrollDeviceParamsAcceptLanguage) Valid() bool {
	switch e {
	case EnrollDeviceParamsAcceptLanguageAr:
		return true
	case EnrollDeviceParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for LogoutParamsAcceptLanguage.
const (
	LogoutParamsAcceptLanguageAr LogoutParamsAcceptLanguage = "ar"
	LogoutParamsAcceptLanguageEn LogoutParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the LogoutParamsAcceptLanguage enum.
func (e LogoutParamsAcceptLanguage) Valid() bool {
	switch e {
	case LogoutParamsAcceptLanguageAr:
		return true
	case LogoutParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for RefreshTokenParamsAcceptLanguage.
const (
	RefreshTokenParamsAcceptLanguageAr RefreshTokenParamsAcceptLanguage = "ar"
	RefreshTokenParamsAcceptLanguageEn RefreshTokenParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the RefreshTokenParamsAcceptLanguage enum.
func (e RefreshTokenParamsAcceptLanguage) Valid() bool {
	switch e {
	case RefreshTokenParamsAcceptLanguageAr:
		return true
	case RefreshTokenParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for CreateAuthSessionParamsAcceptLanguage.
const (
	CreateAuthSessionParamsAcceptLanguageAr CreateAuthSessionParamsAcceptLanguage = "ar"
	CreateAuthSessionParamsAcceptLanguageEn CreateAuthSessionParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the CreateAuthSessionParamsAcceptLanguage enum.
func (e CreateAuthSessionParamsAcceptLanguage) Valid() bool {
	switch e {
	case CreateAuthSessionParamsAcceptLanguageAr:
		return true
	case CreateAuthSessionParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for CheckAuthSessionParamsAcceptLanguage.
const (
	CheckAuthSessionParamsAcceptLanguageAr CheckAuthSessionParamsAcceptLanguage = "ar"
	CheckAuthSessionParamsAcceptLanguageEn CheckAuthSessionParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the CheckAuthSessionParamsAcceptLanguage enum.
func (e CheckAuthSessionParamsAcceptLanguage) Valid() bool {
	switch e {
	case CheckAuthSessionParamsAcceptLanguageAr:
		return true
	case CheckAuthSessionParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for StepUpParamsAcceptLanguage.
const (
	StepUpParamsAcceptLanguageAr StepUpParamsAcceptLanguage = "ar"
	StepUpParamsAcceptLanguageEn StepUpParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the StepUpParamsAcceptLanguage enum.
func (e StepUpParamsAcceptLanguage) Valid() bool {
	switch e {
	case StepUpParamsAcceptLanguageAr:
		return true
	case StepUpParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for StepUpJSONBodyMethod.
const (
	StepUpJSONBodyMethodBiometric StepUpJSONBodyMethod = "biometric"
	StepUpJSONBodyMethodTotp      StepUpJSONBodyMethod = "totp"
	StepUpJSONBodyMethodWebauthn  StepUpJSONBodyMethod = "webauthn"
)

// Valid indicates whether the value is a known member of the StepUpJSONBodyMethod enum.
func (e StepUpJSONBodyMethod) Valid() bool {
	switch e {
	case StepUpJSONBodyMethodBiometric:
		return true
	case StepUpJSONBodyMethodTotp:
		return true
	case StepUpJSONBodyMethodWebauthn:
		return true
	default:
		return false
	}
}

// Defines values for IssueTokenParamsAcceptLanguage.
const (
	IssueTokenParamsAcceptLanguageAr IssueTokenParamsAcceptLanguage = "ar"
	IssueTokenParamsAcceptLanguageEn IssueTokenParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the IssueTokenParamsAcceptLanguage enum.
func (e IssueTokenParamsAcceptLanguage) Valid() bool {
	switch e {
	case IssueTokenParamsAcceptLanguageAr:
		return true
	case IssueTokenParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for DeletePushTokenParamsAcceptLanguage.
const (
	DeletePushTokenParamsAcceptLanguageAr DeletePushTokenParamsAcceptLanguage = "ar"
	DeletePushTokenParamsAcceptLanguageEn DeletePushTokenParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the DeletePushTokenParamsAcceptLanguage enum.
func (e DeletePushTokenParamsAcceptLanguage) Valid() bool {
	switch e {
	case DeletePushTokenParamsAcceptLanguageAr:
		return true
	case DeletePushTokenParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for RegisterPushTokenParamsAcceptLanguage.
const (
	RegisterPushTokenParamsAcceptLanguageAr RegisterPushTokenParamsAcceptLanguage = "ar"
	RegisterPushTokenParamsAcceptLanguageEn RegisterPushTokenParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the RegisterPushTokenParamsAcceptLanguage enum.
func (e RegisterPushTokenParamsAcceptLanguage) Valid() bool {
	switch e {
	case RegisterPushTokenParamsAcceptLanguageAr:
		return true
	case RegisterPushTokenParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for GetHealthParamsAcceptLanguage.
const (
	GetHealthParamsAcceptLanguageAr GetHealthParamsAcceptLanguage = "ar"
	GetHealthParamsAcceptLanguageEn GetHealthParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the GetHealthParamsAcceptLanguage enum.
func (e GetHealthParamsAcceptLanguage) Valid() bool {
	switch e {
	case GetHealthParamsAcceptLanguageAr:
		return true
	case GetHealthParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for GetHolidayCalendarParamsAcceptLanguage.
const (
	GetHolidayCalendarParamsAcceptLanguageAr GetHolidayCalendarParamsAcceptLanguage = "ar"
	GetHolidayCalendarParamsAcceptLanguageEn GetHolidayCalendarParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the GetHolidayCalendarParamsAcceptLanguage enum.
func (e GetHolidayCalendarParamsAcceptLanguage) Valid() bool {
	switch e {
	case GetHolidayCalendarParamsAcceptLanguageAr:
		return true
	case GetHolidayCalendarParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for PutHolidayCalendarParamsAcceptLanguage.
const (
	PutHolidayCalendarParamsAcceptLanguageAr PutHolidayCalendarParamsAcceptLanguage = "ar"
	PutHolidayCalendarParamsAcceptLanguageEn PutHolidayCalendarParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the PutHolidayCalendarParamsAcceptLanguage enum.
func (e PutHolidayCalendarParamsAcceptLanguage) Valid() bool {
	switch e {
	case PutHolidayCalendarParamsAcceptLanguageAr:
		return true
	case PutHolidayCalendarParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for GetMeParamsAcceptLanguage.
const (
	GetMeParamsAcceptLanguageAr GetMeParamsAcceptLanguage = "ar"
	GetMeParamsAcceptLanguageEn GetMeParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the GetMeParamsAcceptLanguage enum.
func (e GetMeParamsAcceptLanguage) Valid() bool {
	switch e {
	case GetMeParamsAcceptLanguageAr:
		return true
	case GetMeParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for GetNotificationPreferencesParamsAcceptLanguage.
const (
	GetNotificationPreferencesParamsAcceptLanguageAr GetNotificationPreferencesParamsAcceptLanguage = "ar"
	GetNotificationPreferencesParamsAcceptLanguageEn GetNotificationPreferencesParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the GetNotificationPreferencesParamsAcceptLanguage enum.
func (e GetNotificationPreferencesParamsAcceptLanguage) Valid() bool {
	switch e {
	case GetNotificationPreferencesParamsAcceptLanguageAr:
		return true
	case GetNotificationPreferencesParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for PutNotificationPreferencesParamsAcceptLanguage.
const (
	PutNotificationPreferencesParamsAcceptLanguageAr PutNotificationPreferencesParamsAcceptLanguage = "ar"
	PutNotificationPreferencesParamsAcceptLanguageEn PutNotificationPreferencesParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the PutNotificationPreferencesParamsAcceptLanguage enum.
func (e PutNotificationPreferencesParamsAcceptLanguage) Valid() bool {
	switch e {
	case PutNotificationPreferencesParamsAcceptLanguageAr:
		return true
	case PutNotificationPreferencesParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListMySessionsParamsAcceptLanguage.
const (
	ListMySessionsParamsAcceptLanguageAr ListMySessionsParamsAcceptLanguage = "ar"
	ListMySessionsParamsAcceptLanguageEn ListMySessionsParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListMySessionsParamsAcceptLanguage enum.
func (e ListMySessionsParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListMySessionsParamsAcceptLanguageAr:
		return true
	case ListMySessionsParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for EndMySessionParamsAcceptLanguage.
const (
	EndMySessionParamsAcceptLanguageAr EndMySessionParamsAcceptLanguage = "ar"
	EndMySessionParamsAcceptLanguageEn EndMySessionParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the EndMySessionParamsAcceptLanguage enum.
func (e EndMySessionParamsAcceptLanguage) Valid() bool {
	switch e {
	case EndMySessionParamsAcceptLanguageAr:
		return true
	case EndMySessionParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListNotificationsParamsGroup.
const (
	ListNotificationsParamsGroupFyi     ListNotificationsParamsGroup = "fyi"
	ListNotificationsParamsGroupNeedsMe ListNotificationsParamsGroup = "needs_me"
	ListNotificationsParamsGroupWaiting ListNotificationsParamsGroup = "waiting"
)

// Valid indicates whether the value is a known member of the ListNotificationsParamsGroup enum.
func (e ListNotificationsParamsGroup) Valid() bool {
	switch e {
	case ListNotificationsParamsGroupFyi:
		return true
	case ListNotificationsParamsGroupNeedsMe:
		return true
	case ListNotificationsParamsGroupWaiting:
		return true
	default:
		return false
	}
}

// Defines values for ListNotificationsParamsAcceptLanguage.
const (
	ListNotificationsParamsAcceptLanguageAr ListNotificationsParamsAcceptLanguage = "ar"
	ListNotificationsParamsAcceptLanguageEn ListNotificationsParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListNotificationsParamsAcceptLanguage enum.
func (e ListNotificationsParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListNotificationsParamsAcceptLanguageAr:
		return true
	case ListNotificationsParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for AcknowledgeNotificationParamsAcceptLanguage.
const (
	AcknowledgeNotificationParamsAcceptLanguageAr AcknowledgeNotificationParamsAcceptLanguage = "ar"
	AcknowledgeNotificationParamsAcceptLanguageEn AcknowledgeNotificationParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the AcknowledgeNotificationParamsAcceptLanguage enum.
func (e AcknowledgeNotificationParamsAcceptLanguage) Valid() bool {
	switch e {
	case AcknowledgeNotificationParamsAcceptLanguageAr:
		return true
	case AcknowledgeNotificationParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for HardClosePeriodParamsAcceptLanguage.
const (
	HardClosePeriodParamsAcceptLanguageAr HardClosePeriodParamsAcceptLanguage = "ar"
	HardClosePeriodParamsAcceptLanguageEn HardClosePeriodParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the HardClosePeriodParamsAcceptLanguage enum.
func (e HardClosePeriodParamsAcceptLanguage) Valid() bool {
	switch e {
	case HardClosePeriodParamsAcceptLanguageAr:
		return true
	case HardClosePeriodParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for SoftClosePeriodParamsAcceptLanguage.
const (
	SoftClosePeriodParamsAcceptLanguageAr SoftClosePeriodParamsAcceptLanguage = "ar"
	SoftClosePeriodParamsAcceptLanguageEn SoftClosePeriodParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the SoftClosePeriodParamsAcceptLanguage enum.
func (e SoftClosePeriodParamsAcceptLanguage) Valid() bool {
	switch e {
	case SoftClosePeriodParamsAcceptLanguageAr:
		return true
	case SoftClosePeriodParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for OpenAuditAdjustmentPeriodParamsAcceptLanguage.
const (
	OpenAuditAdjustmentPeriodParamsAcceptLanguageAr OpenAuditAdjustmentPeriodParamsAcceptLanguage = "ar"
	OpenAuditAdjustmentPeriodParamsAcceptLanguageEn OpenAuditAdjustmentPeriodParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the OpenAuditAdjustmentPeriodParamsAcceptLanguage enum.
func (e OpenAuditAdjustmentPeriodParamsAcceptLanguage) Valid() bool {
	switch e {
	case OpenAuditAdjustmentPeriodParamsAcceptLanguageAr:
		return true
	case OpenAuditAdjustmentPeriodParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for ListSodMatrixParamsAcceptLanguage.
const (
	ListSodMatrixParamsAcceptLanguageAr ListSodMatrixParamsAcceptLanguage = "ar"
	ListSodMatrixParamsAcceptLanguageEn ListSodMatrixParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the ListSodMatrixParamsAcceptLanguage enum.
func (e ListSodMatrixParamsAcceptLanguage) Valid() bool {
	switch e {
	case ListSodMatrixParamsAcceptLanguageAr:
		return true
	case ListSodMatrixParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for CreateSodRuleParamsAcceptLanguage.
const (
	CreateSodRuleParamsAcceptLanguageAr CreateSodRuleParamsAcceptLanguage = "ar"
	CreateSodRuleParamsAcceptLanguageEn CreateSodRuleParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the CreateSodRuleParamsAcceptLanguage enum.
func (e CreateSodRuleParamsAcceptLanguage) Valid() bool {
	switch e {
	case CreateSodRuleParamsAcceptLanguageAr:
		return true
	case CreateSodRuleParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for GetStatusParamsAcceptLanguage.
const (
	GetStatusParamsAcceptLanguageAr GetStatusParamsAcceptLanguage = "ar"
	GetStatusParamsAcceptLanguageEn GetStatusParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the GetStatusParamsAcceptLanguage enum.
func (e GetStatusParamsAcceptLanguage) Valid() bool {
	switch e {
	case GetStatusParamsAcceptLanguageAr:
		return true
	case GetStatusParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Defines values for SubscribeEventsParamsAcceptLanguage.
const (
	SubscribeEventsParamsAcceptLanguageAr SubscribeEventsParamsAcceptLanguage = "ar"
	SubscribeEventsParamsAcceptLanguageEn SubscribeEventsParamsAcceptLanguage = "en"
)

// Valid indicates whether the value is a known member of the SubscribeEventsParamsAcceptLanguage enum.
func (e SubscribeEventsParamsAcceptLanguage) Valid() bool {
	switch e {
	case SubscribeEventsParamsAcceptLanguageAr:
		return true
	case SubscribeEventsParamsAcceptLanguageEn:
		return true
	default:
		return false
	}
}

// Actor defines model for Actor.
type Actor struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// AlertRule defines model for AlertRule.
type AlertRule struct {
	Builtin        *bool                  `json:"builtin,omitempty"`
	Channel        string                 `json:"channel"`
	Condition      map[string]interface{} `json:"condition"`
	DocumentType   string                 `json:"document_type"`
	Enabled        bool                   `json:"enabled"`
	Id             string                 `json:"id"`
	Mode           AlertRuleMode          `json:"mode"`
	RecipientRoles []string               `json:"recipient_roles"`
	Severity       Severity               `json:"severity"`
}

// AlertRuleMode defines model for AlertRule.Mode.
type AlertRuleMode string

// AlertRuleInput defines model for AlertRuleInput.
type AlertRuleInput struct {
	Builtin        *bool                  `json:"builtin,omitempty"`
	Channel        string                 `json:"channel"`
	Condition      map[string]interface{} `json:"condition"`
	DocumentType   string                 `json:"document_type"`
	Mode           AlertRuleInputMode     `json:"mode"`
	RecipientRoles []string               `json:"recipient_roles"`
	Severity       Severity               `json:"severity"`
}

// AlertRuleInputMode defines model for AlertRuleInput.Mode.
type AlertRuleInputMode string

// AllowedAction defines model for AllowedAction.
type AllowedAction string

// ApprovalCard defines model for ApprovalCard.
type ApprovalCard struct {
	AllowedActions []AllowedAction `json:"allowed_actions"`

	// Amount Decimal amount as a string plus an ISO 4217 currency code. Never a float.
	Amount     Money    `json:"amount"`
	DeepLink   string   `json:"deep_link"`
	DocNumber  string   `json:"doc_number"`
	DocType    string   `json:"doc_type"`
	FraudHints []string `json:"fraud_hints"`
	Party      *string  `json:"party,omitempty"`
	RequestId  string   `json:"request_id"`
	Requester  Actor    `json:"requester"`
	Severity   Severity `json:"severity"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
	WaitingSince time.Time    `json:"waiting_since"`
}

// ApprovalDecision defines model for ApprovalDecision.
type ApprovalDecision struct {
	DecidedAt *time.Time    `json:"decided_at,omitempty"`
	DecidedBy *Actor        `json:"decided_by,omitempty"`
	RequestId string        `json:"request_id"`
	State     ApprovalState `json:"state"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
}

// ApprovalDetail defines model for ApprovalDetail.
type ApprovalDetail struct {
	AllowedActions []AllowedAction `json:"allowed_actions"`

	// Amount Decimal amount as a string plus an ISO 4217 currency code. Never a float.
	Amount    Money `json:"amount"`
	Decisions *[]struct {
		At       time.Time                       `json:"at"`
		By       Actor                           `json:"by"`
		Comment  *string                         `json:"comment,omitempty"`
		Decision ApprovalDetailDecisionsDecision `json:"decision"`
		HashSeen string                          `json:"hash_seen"`
	} `json:"decisions,omitempty"`
	DeepLink   string   `json:"deep_link"`
	DocNumber  string   `json:"doc_number"`
	DocType    string   `json:"doc_type"`
	FraudHints []string `json:"fraud_hints"`
	Party      *string  `json:"party,omitempty"`
	RequestId  string   `json:"request_id"`
	Requester  Actor    `json:"requester"`
	Severity   Severity `json:"severity"`

	// Snapshot The document as submitted
	Snapshot map[string]interface{} `json:"snapshot"`

	// SnapshotHash sha256 of the canonical snapshot (R2.11); shown to approvers
	SnapshotHash string        `json:"snapshot_hash"`
	State        ApprovalState `json:"state"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
	WaitingSince time.Time    `json:"waiting_since"`
}

// ApprovalDetailDecisionsDecision defines model for ApprovalDetail.Decisions.Decision.
type ApprovalDetailDecisionsDecision string

// ApprovalMatrixRule Approval routing for one document type (R2.2). The engine that consumes it is the approvals module.
type ApprovalMatrixRule struct {
	ApprovalRequestId *string `json:"approval_request_id,omitempty"`

	// BelowThresholdRole Any one holder of this role may register the document below the threshold
	BelowThresholdRole string `json:"below_threshold_role"`
	DocumentType       string `json:"document_type"`

	// FinalGateRole Named final gate; not delegable
	FinalGateRole string `json:"final_gate_role"`

	// FirstApproverRole Independent first approver at or above the threshold
	FirstApproverRole string             `json:"first_approver_role"`
	Id                openapi_types.UUID `json:"id"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion             `json:"state_version"`
	Status       ApprovalMatrixRuleStatus `json:"status"`

	// Threshold At or above this amount the first approver and the final gate both apply
	Threshold Money `json:"threshold"`

	// VotingAny When set with `voting_of`, the company requires any N of M
	VotingAny *int `json:"voting_any,omitempty"`
	VotingOf  *int `json:"voting_of,omitempty"`
}

// ApprovalMatrixRuleStatus defines model for ApprovalMatrixRule.Status.
type ApprovalMatrixRuleStatus string

// ApprovalMatrixRuleWrite defines model for ApprovalMatrixRuleWrite.
type ApprovalMatrixRuleWrite struct {
	BelowThresholdRole string `json:"below_threshold_role"`
	DocumentType       string `json:"document_type"`
	FinalGateRole      string `json:"final_gate_role"`
	FirstApproverRole  string `json:"first_approver_role"`

	// Threshold Decimal amount as a string plus an ISO 4217 currency code. Never a float.
	Threshold Money `json:"threshold"`
	VotingAny *int  `json:"voting_any,omitempty"`
	VotingOf  *int  `json:"voting_of,omitempty"`
}

// ApprovalState defines model for ApprovalState.
type ApprovalState string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Actor Actor                   `json:"actor"`
	After *map[string]interface{} `json:"after,omitempty"`

	// At Database-assigned (B8)
	At       time.Time               `json:"at"`
	Before   *map[string]interface{} `json:"before,omitempty"`
	ChainSeq int                     `json:"chain_seq"`
	EventId  string                  `json:"event_id"`
	Hash     string                  `json:"hash"`
	PrevHash *string                 `json:"prev_hash,omitempty"`
	Ref      *string                 `json:"ref,omitempty"`
	Type     string                  `json:"type"`
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	Challenges struct {
		// Passkey WebAuthn request options when a passkey challenge is available
		Passkey      *map[string]interface{} `json:"passkey,omitempty"`
		TotpRequired *bool                   `json:"totp_required,omitempty"`
	} `json:"challenges"`
	SessionId string `json:"session_id"`

	// Verified True once every required factor has been verified
	Verified *bool `json:"verified,omitempty"`
}

// ChainVerification defines model for ChainVerification.
type ChainVerification struct {
	// AnchoredHeadMatches Recomputed head at each anchored chain_seq equals the anchored value (B11)
	AnchoredHeadMatches bool `json:"anchored_head_matches"`

	// Count Rows walked
	Count int `json:"count"`

	// FirstBreak Present only when `intact` is false; the first row whose hash or prev_hash failed (B6, B7)
	FirstBreak *struct {
		ChainSeq int     `json:"chain_seq"`
		Reason   *string `json:"reason,omitempty"`
		RowId    string  `json:"row_id"`
		Table    string  `json:"table"`
	} `json:"first_break,omitempty"`
	Intact bool `json:"intact"`
}

// DecisionMeta Meta for approval decisions. `notice` carries `ALREADY_DECIDED` when a concurrent decision won (D7).
type DecisionMeta struct {
	// AsOf Server time the response was computed, UTC
	AsOf   time.Time           `json:"as_of"`
	Notice *DecisionMetaNotice `json:"notice,omitempty"`

	// RequestId Correlates the response with logs and audit rows
	RequestId            string                 `json:"request_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DecisionMetaNotice defines model for DecisionMeta.Notice.
type DecisionMetaNotice string

// Empty Success with no payload
type Empty = map[string]interface{}

// Error defines model for Error.
type Error struct {
	// Code The closed set of error codes from docs/spec/04-api-contracts.md.
	Code ErrorCode `json:"code"`

	// Details Code-specific detail, e.g. `{ field }` for VALIDATION_ERROR or `{ current }` for CONFLICT
	Details map[string]interface{} `json:"details"`

	// Message Human readable, localised by Accept-Language
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

// ErrorCode The closed set of error codes from docs/spec/04-api-contracts.md.
type ErrorCode string

// ErrorEnvelope Returned on every failure path including 429 and gateway errors (A17).
type ErrorEnvelope struct {
	Error Error `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Commit Git commit of the running build
	Commit string               `json:"commit"`
	Status HealthResponseStatus `json:"status"`

	// Version Semantic version or tag of the running build
	Version string `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Holiday defines model for Holiday.
type Holiday struct {
	Date openapi_types.Date `json:"date"`
	Name string             `json:"name"`
}

// HolidayCalendar Company business-hours calendar (ADR-12). Clocks count only time inside
// `business_open`–`business_close` on days that are neither weekend nor holiday.
type HolidayCalendar struct {
	// BusinessClose Local end of the working day, HH:MM (24-hour), after `business_open`
	//
	// Examples: 20:00
	BusinessClose string `json:"business_close"`

	// BusinessOpen Local start of the working day, HH:MM (24-hour)
	//
	// Examples: 08:00
	BusinessOpen string    `json:"business_open"`
	Holidays     []Holiday `json:"holidays"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`

	// Timezone Examples: Asia/Dubai
	Timezone string    `json:"timezone"`
	Weekend  []Weekday `json:"weekend"`
}

// HolidayCalendarWrite Body of POST /holiday-calendar. `state_version` is not accepted from the client.
type HolidayCalendarWrite struct {
	BusinessClose string    `json:"business_close"`
	BusinessOpen  string    `json:"business_open"`
	Holidays      []Holiday `json:"holidays"`
	Timezone      string    `json:"timezone"`
	Weekend       []Weekday `json:"weekend"`
}

// Meta Present on every success response.
type Meta struct {
	// AsOf Server time the response was computed, UTC
	AsOf time.Time `json:"as_of"`

	// RequestId Correlates the response with logs and audit rows
	RequestId            string                 `json:"request_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Money Decimal amount as a string plus an ISO 4217 currency code. Never a float.
type Money struct {
	// Amount Examples: 1234.56
	Amount string `json:"amount"`

	// Currency Examples: AED
	Currency string `json:"currency"`
}

// NotificationItem defines model for NotificationItem.
type NotificationItem struct {
	AllowedActions []AllowedAction `json:"allowed_actions"`
	Amount         *Money          `json:"amount,omitempty"`
	DeepLink       string          `json:"deep_link"`
	DocNumber      *string         `json:"doc_number,omitempty"`
	DocType        string          `json:"doc_type"`
	EventId        string          `json:"event_id"`
	Party          *string         `json:"party,omitempty"`
	Requester      Actor           `json:"requester"`
	Severity       Severity        `json:"severity"`
	WaitingSince   time.Time       `json:"waiting_since"`
}

// NotificationPreferences defines model for NotificationPreferences.
type NotificationPreferences struct {
	Channels *[]struct {
		Channel   NotificationPreferencesChannelsChannel `json:"channel"`
		DeviceId  *string                                `json:"device_id,omitempty"`
		Enabled   bool                                   `json:"enabled"`
		EventType string                                 `json:"event_type"`
	} `json:"channels,omitempty"`
	QuietHours *struct {
		End *string `json:"end,omitempty"`

		// Start Local time HH:MM
		Start *string `json:"start,omitempty"`

		// Zone IANA time zone. Critical is never suppressed inside the window.
		Zone *string `json:"zone,omitempty"`
	} `json:"quiet_hours,omitempty"`
}

// NotificationPreferencesChannelsChannel defines model for NotificationPreferences.Channels.Channel.
type NotificationPreferencesChannelsChannel string

// PageMeta Meta for list responses. `total` is present only where cheap.
type PageMeta struct {
	// AsOf Server time the response was computed, UTC
	AsOf       time.Time `json:"as_of"`
	NextCursor *string   `json:"next_cursor,omitempty"`

	// RequestId Correlates the response with logs and audit rows
	RequestId            string                 `json:"request_id"`
	Total                *int                   `json:"total,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Period defines model for Period.
type Period struct {
	EndDate    openapi_types.Date `json:"end_date"`
	FiscalYear int                `json:"fiscal_year"`
	Id         openapi_types.UUID `json:"id"`
	Kind       PeriodKind         `json:"kind"`

	// Month Null on the audit-adjustment period
	Month     *int               `json:"month,omitempty"`
	StartDate openapi_types.Date `json:"start_date"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
	Status       PeriodStatus `json:"status"`
}

// PeriodApproval Approval id granted by the approvals module before a Stakeholder close or open.
type PeriodApproval struct {
	ApprovalId string `json:"approval_id"`
}

// PeriodKind defines model for PeriodKind.
type PeriodKind string

// PeriodStatus defines model for PeriodStatus.
type PeriodStatus string

// Platform defines model for Platform.
type Platform string

// Severity defines model for Severity.
type Severity string

// SodRule One row of the segregation-of-duties matrix (R1.13).
type SodRule struct {
	// ApprovalRequestId Set when the mutation is waiting on the approval engine
	ApprovalRequestId *string            `json:"approval_request_id,omitempty"`
	Id                openapi_types.UUID `json:"id"`

	// Kind `role_pair` is two roles one person must not hold together. `action_pair` is two
	// actions one person must not both perform on a document (enter and approve, receive
	// and count, create vendor and pay vendor, request correction and approve correction).
	Kind SodRuleKind `json:"kind"`

	// LeftCode Role name or permission code
	LeftCode string `json:"left_code"`

	// RightCode Role name or permission code
	RightCode string `json:"right_code"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion  `json:"state_version"`
	Status       SodRuleStatus `json:"status"`
}

// SodRuleKind `role_pair` is two roles one person must not hold together. `action_pair` is two
// actions one person must not both perform on a document (enter and approve, receive
// and count, create vendor and pay vendor, request correction and approve correction).
type SodRuleKind string

// SodRuleStatus defines model for SodRule.Status.
type SodRuleStatus string

// SodRuleWrite defines model for SodRuleWrite.
type SodRuleWrite struct {
	Kind      SodRuleWriteKind `json:"kind"`
	LeftCode  string           `json:"left_code"`
	RightCode string           `json:"right_code"`
}

// SodRuleWriteKind defines model for SodRuleWrite.Kind.
type SodRuleWriteKind string

// StateVersion Optimistic concurrency version; bumped on every transition
type StateVersion = int

// StatusResponse Operator status (A20, I16). Absent data is `null` with a reason, never a fabricated value.
type StatusResponse struct {
	// ClockDriftMs Signed drift between the database clock and NTP, in milliseconds
	ClockDriftMs          int       `json:"clock_drift_ms"`
	LastBackup            StatusRun `json:"last_backup"`
	LastBankFeed          StatusRun `json:"last_bank_feed"`
	LastChainVerification StatusRun `json:"last_chain_verification"`

	// QueueDepth Jobs waiting in the outbox
	QueueDepth int `json:"queue_depth"`

	// RecoveryPointInForce Which recovery point currently holds, given WAL archive lag
	RecoveryPointInForce StatusResponseRecoveryPointInForce `json:"recovery_point_in_force"`
	WorkerHealth         StatusResponseWorkerHealth         `json:"worker_health"`
}

// StatusResponseRecoveryPointInForce Which recovery point currently holds, given WAL archive lag
type StatusResponseRecoveryPointInForce string

// StatusResponseWorkerHealth defines model for StatusResponse.WorkerHealth.
type StatusResponseWorkerHealth string

// StatusRun defines model for StatusRun.
type StatusRun struct {
	At     *time.Time      `json:"at"`
	Detail *string         `json:"detail,omitempty"`
	Result StatusRunResult `json:"result"`
}

// StatusRunResult defines model for StatusRun.Result.
type StatusRunResult string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds; at most 900
	ExpiresIn     int                          `json:"expires_in"`
	RefreshToken  string                       `json:"refresh_token"`
	StepUpMethods []TokenResponseStepUpMethods `json:"step_up_methods"`
	User          User                         `json:"user"`
}

// TokenResponseStepUpMethods defines model for TokenResponse.StepUpMethods.
type TokenResponseStepUpMethods string

// User defines model for User.
type User struct {
	CompanyId string   `json:"company_id"`
	Id        string   `json:"id"`
	Name      string   `json:"name"`
	Personas  []string `json:"personas"`
	Roles     []string `json:"roles"`
}

// UserSession A listable authenticated session bound to one enrolled device (R1.15).
type UserSession struct {
	CreatedAt time.Time `json:"created_at"`

	// Current True when this session issued the access token of the caller
	Current    *bool      `json:"current,omitempty"`
	DeviceId   string     `json:"device_id"`
	DeviceName *string    `json:"device_name,omitempty"`
	Id         string     `json:"id"`
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	Platform   *Platform  `json:"platform,omitempty"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
}

// Weekday defines model for Weekday.
type Weekday string

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage string

// ApprovalId defines model for ApprovalId.
type ApprovalId = string

// Cursor defines model for Cursor.
type Cursor = string

// EventId defines model for EventId.
type EventId = string

// FiscalYear defines model for FiscalYear.
type FiscalYear = int

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// IfMatch defines model for IfMatch.
type IfMatch = string

// IfMatchRequired defines model for IfMatchRequired.
type IfMatchRequired = string

// Limit defines model for Limit.
type Limit = int

// PeriodId defines model for PeriodId.
type PeriodId = openapi_types.UUID

// SessionId defines model for SessionId.
type SessionId = string

// UserSessionId defines model for UserSessionId.
type UserSessionId = string

// BadRequest Returned on every failure path including 429 and gateway errors (A17).
type BadRequest = ErrorEnvelope

// Conflict Returned on every failure path including 429 and gateway errors (A17).
type Conflict = ErrorEnvelope

// Forbidden Returned on every failure path including 429 and gateway errors (A17).
type Forbidden = ErrorEnvelope

// InternalError Returned on every failure path including 429 and gateway errors (A17).
type InternalError = ErrorEnvelope

// NotFound Returned on every failure path including 429 and gateway errors (A17).
type NotFound = ErrorEnvelope

// RateLimited Returned on every failure path including 429 and gateway errors (A17).
type RateLimited = ErrorEnvelope

// Unauthorized Returned on every failure path including 429 and gateway errors (A17).
type Unauthorized = ErrorEnvelope

// Unavailable Returned on every failure path including 429 and gateway errors (A17).
type Unavailable = ErrorEnvelope

// ListAlertRulesParams defines parameters for ListAlertRules.
type ListAlertRulesParams struct {
	DocumentType *string `form:"document_type,omitempty" json:"document_type,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListAlertRulesParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListAlertRulesParamsAcceptLanguage defines parameters for ListAlertRules.
type ListAlertRulesParamsAcceptLanguage string

// CreateAlertRuleParams defines parameters for CreateAlertRule.
type CreateAlertRuleParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *CreateAlertRuleParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// CreateAlertRuleParamsAcceptLanguage defines parameters for CreateAlertRule.
type CreateAlertRuleParamsAcceptLanguage string

// ListApprovalMatrixParams defines parameters for ListApprovalMatrix.
type ListApprovalMatrixParams struct {
	// Cursor Opaque cursor from `meta.next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListApprovalMatrixParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListApprovalMatrixParamsAcceptLanguage defines parameters for ListApprovalMatrix.
type ListApprovalMatrixParamsAcceptLanguage string

// CreateApprovalMatrixRuleParams defines parameters for CreateApprovalMatrixRule.
type CreateApprovalMatrixRuleParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. A mismatch is `409 CONFLICT` with the current
	// state in `error.details.current`.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *CreateApprovalMatrixRuleParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// CreateApprovalMatrixRuleParamsAcceptLanguage defines parameters for CreateApprovalMatrixRule.
type CreateApprovalMatrixRuleParamsAcceptLanguage string

// ListApprovalInboxParams defines parameters for ListApprovalInbox.
type ListApprovalInboxParams struct {
	State *ListApprovalInboxParamsState `form:"state,omitempty" json:"state,omitempty"`

	// Cursor Opaque cursor from `meta.next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListApprovalInboxParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListApprovalInboxParamsState defines parameters for ListApprovalInbox.
type ListApprovalInboxParamsState string

// ListApprovalInboxParamsAcceptLanguage defines parameters for ListApprovalInbox.
type ListApprovalInboxParamsAcceptLanguage string

// GetApprovalParams defines parameters for GetApproval.
type GetApprovalParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *GetApprovalParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetApprovalParamsAcceptLanguage defines parameters for GetApproval.
type GetApprovalParamsAcceptLanguage string

// ApproveApprovalJSONBody defines parameters for ApproveApproval.
type ApproveApprovalJSONBody struct {
	Comment *string `json:"comment,omitempty"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
	StepUpToken  *string      `json:"step_up_token,omitempty"`
}

// ApproveApprovalParams defines parameters for ApproveApproval.
type ApproveApprovalParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. A mismatch is `409 CONFLICT` with the current
	// state in `error.details.current`.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ApproveApprovalParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ApproveApprovalParamsAcceptLanguage defines parameters for ApproveApproval.
type ApproveApprovalParamsAcceptLanguage string

// RejectApprovalJSONBody defines parameters for RejectApproval.
type RejectApprovalJSONBody struct {
	Reason string `json:"reason"`

	// StateVersion Optimistic concurrency version; bumped on every transition
	StateVersion StateVersion `json:"state_version"`
}

// RejectApprovalParams defines parameters for RejectApproval.
type RejectApprovalParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. A mismatch is `409 CONFLICT` with the current
	// state in `error.details.current`.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *RejectApprovalParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// RejectApprovalParamsAcceptLanguage defines parameters for RejectApproval.
type RejectApprovalParamsAcceptLanguage string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	// Ref Document or entity reference (id or number) the event is about
	Ref  *string    `form:"ref,omitempty" json:"ref,omitempty"`
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Type Event type, e.g. approval.decided
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Cursor Opaque cursor from `meta.next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListAuditEventsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListAuditEventsParamsAcceptLanguage defines parameters for ListAuditEvents.
type ListAuditEventsParamsAcceptLanguage string

// VerifyAuditChainParams defines parameters for VerifyAuditChain.
type VerifyAuditChainParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *VerifyAuditChainParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// VerifyAuditChainParamsAcceptLanguage defines parameters for VerifyAuditChain.
type VerifyAuditChainParamsAcceptLanguage string

// EnrollDeviceJSONBody defines parameters for EnrollDevice.
type EnrollDeviceJSONBody struct {
	AppVersion string   `json:"app_version"`
	DeviceName string   `json:"device_name"`
	Platform   Platform `json:"platform"`

	// PublicKey JWK of the device public key (EC P-256 or RSA)
	PublicKey map[string]interface{} `json:"public_key"`
}

// EnrollDeviceParams defines parameters for EnrollDevice.
type EnrollDeviceParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *EnrollDeviceParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// EnrollDeviceParamsAcceptLanguage defines parameters for EnrollDevice.
type EnrollDeviceParamsAcceptLanguage string

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *LogoutParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// LogoutParamsAcceptLanguage defines parameters for Logout.
type LogoutParamsAcceptLanguage string

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenParams defines parameters for RefreshToken.
type RefreshTokenParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *RefreshTokenParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// RefreshTokenParamsAcceptLanguage defines parameters for RefreshToken.
type RefreshTokenParamsAcceptLanguage string

// CreateAuthSessionJSONBody defines parameters for CreateAuthSession.
type CreateAuthSessionJSONBody struct {
	LoginName string `json:"login_name"`
}

// CreateAuthSessionParams defines parameters for CreateAuthSession.
type CreateAuthSessionParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *CreateAuthSessionParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// CreateAuthSessionParamsAcceptLanguage defines parameters for CreateAuthSession.
type CreateAuthSessionParamsAcceptLanguage string

// CheckAuthSessionJSONBody defines parameters for CheckAuthSession.
type CheckAuthSessionJSONBody struct {
	Password *string `json:"password,omitempty"`
	Totp     *string `json:"totp,omitempty"`

	// WebauthnAssertion WebAuthn assertion as produced by the platform authenticator
	WebauthnAssertion *map[string]interface{} `json:"webauthn_assertion,omitempty"`
}

// CheckAuthSessionParams defines parameters for CheckAuthSession.
type CheckAuthSessionParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *CheckAuthSessionParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// CheckAuthSessionParamsAcceptLanguage defines parameters for CheckAuthSession.
type CheckAuthSessionParamsAcceptLanguage string

// StepUpJSONBody defines parameters for StepUp.
type StepUpJSONBody struct {
	// Code TOTP code, or the serialised assertion for webauthn and biometric
	Code   string               `json:"code"`
	Method StepUpJSONBodyMethod `json:"method"`
}

// StepUpParams defines parameters for StepUp.
type StepUpParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *StepUpParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// StepUpParamsAcceptLanguage defines parameters for StepUp.
type StepUpParamsAcceptLanguage string

// StepUpJSONBodyMethod defines parameters for StepUp.
type StepUpJSONBodyMethod string

// IssueTokenJSONBody defines parameters for IssueToken.
type IssueTokenJSONBody struct {
	DeviceId  string `json:"device_id"`
	SessionId string `json:"session_id"`
}

// IssueTokenParams defines parameters for IssueToken.
type IssueTokenParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *IssueTokenParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// IssueTokenParamsAcceptLanguage defines parameters for IssueToken.
type IssueTokenParamsAcceptLanguage string

// DeletePushTokenParams defines parameters for DeletePushToken.
type DeletePushTokenParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *DeletePushTokenParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// DeletePushTokenParamsAcceptLanguage defines parameters for DeletePushToken.
type DeletePushTokenParamsAcceptLanguage string

// RegisterPushTokenJSONBody defines parameters for RegisterPushToken.
type RegisterPushTokenJSONBody struct {
	AppVersion string   `json:"app_version"`
	Platform   Platform `json:"platform"`
	Token      string   `json:"token"`
}

// RegisterPushTokenParams defines parameters for RegisterPushToken.
type RegisterPushTokenParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *RegisterPushTokenParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// RegisterPushTokenParamsAcceptLanguage defines parameters for RegisterPushToken.
type RegisterPushTokenParamsAcceptLanguage string

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *GetHealthParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetHealthParamsAcceptLanguage defines parameters for GetHealth.
type GetHealthParamsAcceptLanguage string

// GetHolidayCalendarParams defines parameters for GetHolidayCalendar.
type GetHolidayCalendarParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *GetHolidayCalendarParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetHolidayCalendarParamsAcceptLanguage defines parameters for GetHolidayCalendar.
type GetHolidayCalendarParamsAcceptLanguage string

// PutHolidayCalendarParams defines parameters for PutHolidayCalendar.
type PutHolidayCalendarParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. Required on period and holiday-calendar
	// writes. A mismatch is `409 CONFLICT` with the current state in `error.details.current`.
	// The first holiday-calendar write sends `0`.
	IfMatch IfMatchRequired `json:"If-Match"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *PutHolidayCalendarParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PutHolidayCalendarParamsAcceptLanguage defines parameters for PutHolidayCalendar.
type PutHolidayCalendarParamsAcceptLanguage string

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *GetMeParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetMeParamsAcceptLanguage defines parameters for GetMe.
type GetMeParamsAcceptLanguage string

// GetNotificationPreferencesParams defines parameters for GetNotificationPreferences.
type GetNotificationPreferencesParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *GetNotificationPreferencesParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetNotificationPreferencesParamsAcceptLanguage defines parameters for GetNotificationPreferences.
type GetNotificationPreferencesParamsAcceptLanguage string

// PutNotificationPreferencesParams defines parameters for PutNotificationPreferences.
type PutNotificationPreferencesParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *PutNotificationPreferencesParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// PutNotificationPreferencesParamsAcceptLanguage defines parameters for PutNotificationPreferences.
type PutNotificationPreferencesParamsAcceptLanguage string

// ListMySessionsParams defines parameters for ListMySessions.
type ListMySessionsParams struct {
	// Cursor Opaque cursor from `meta.next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListMySessionsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListMySessionsParamsAcceptLanguage defines parameters for ListMySessions.
type ListMySessionsParamsAcceptLanguage string

// EndMySessionParams defines parameters for EndMySession.
type EndMySessionParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. A mismatch is `409 CONFLICT` with the current
	// state in `error.details.current`.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *EndMySessionParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// EndMySessionParamsAcceptLanguage defines parameters for EndMySession.
type EndMySessionParamsAcceptLanguage string

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	Group  *ListNotificationsParamsGroup `form:"group,omitempty" json:"group,omitempty"`
	Cursor *string                       `form:"cursor,omitempty" json:"cursor,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListNotificationsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListNotificationsParamsGroup defines parameters for ListNotifications.
type ListNotificationsParamsGroup string

// ListNotificationsParamsAcceptLanguage defines parameters for ListNotifications.
type ListNotificationsParamsAcceptLanguage string

// AcknowledgeNotificationParams defines parameters for AcknowledgeNotification.
type AcknowledgeNotificationParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *AcknowledgeNotificationParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// AcknowledgeNotificationParamsAcceptLanguage defines parameters for AcknowledgeNotification.
type AcknowledgeNotificationParamsAcceptLanguage string

// HardClosePeriodParams defines parameters for HardClosePeriod.
type HardClosePeriodParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. Required on period and holiday-calendar
	// writes. A mismatch is `409 CONFLICT` with the current state in `error.details.current`.
	// The first holiday-calendar write sends `0`.
	IfMatch IfMatchRequired `json:"If-Match"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *HardClosePeriodParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// HardClosePeriodParamsAcceptLanguage defines parameters for HardClosePeriod.
type HardClosePeriodParamsAcceptLanguage string

// SoftClosePeriodParams defines parameters for SoftClosePeriod.
type SoftClosePeriodParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. Required on period and holiday-calendar
	// writes. A mismatch is `409 CONFLICT` with the current state in `error.details.current`.
	// The first holiday-calendar write sends `0`.
	IfMatch IfMatchRequired `json:"If-Match"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *SoftClosePeriodParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// SoftClosePeriodParamsAcceptLanguage defines parameters for SoftClosePeriod.
type SoftClosePeriodParamsAcceptLanguage string

// OpenAuditAdjustmentPeriodParams defines parameters for OpenAuditAdjustmentPeriod.
type OpenAuditAdjustmentPeriodParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. Required on period and holiday-calendar
	// writes. A mismatch is `409 CONFLICT` with the current state in `error.details.current`.
	// The first holiday-calendar write sends `0`.
	IfMatch IfMatchRequired `json:"If-Match"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *OpenAuditAdjustmentPeriodParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// OpenAuditAdjustmentPeriodParamsAcceptLanguage defines parameters for OpenAuditAdjustmentPeriod.
type OpenAuditAdjustmentPeriodParamsAcceptLanguage string

// ListSodMatrixParams defines parameters for ListSodMatrix.
type ListSodMatrixParams struct {
	// Cursor Opaque cursor from `meta.next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *ListSodMatrixParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// ListSodMatrixParamsAcceptLanguage defines parameters for ListSodMatrix.
type ListSodMatrixParamsAcceptLanguage string

// CreateSodRuleParams defines parameters for CreateSodRule.
type CreateSodRuleParams struct {
	// IdempotencyKey UUID chosen by the client. The server stores the response for 24 hours and replays it for a
	// repeated key with the same body; a different body with the same key is `409 CONFLICT`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch The `state_version` the client last saw. A mismatch is `409 CONFLICT` with the current
	// state in `error.details.current`.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *CreateSodRuleParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// CreateSodRuleParamsAcceptLanguage defines parameters for CreateSodRule.
type CreateSodRuleParamsAcceptLanguage string

// GetStatusParams defines parameters for GetStatus.
type GetStatusParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *GetStatusParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// GetStatusParamsAcceptLanguage defines parameters for GetStatus.
type GetStatusParamsAcceptLanguage string

// SubscribeEventsParams defines parameters for SubscribeEvents.
type SubscribeEventsParams struct {
	// AcceptLanguage `en` or `ar`. Affects messages and print formats, never data.
	AcceptLanguage *SubscribeEventsParamsAcceptLanguage `json:"Accept-Language,omitempty"`
}

// SubscribeEventsParamsAcceptLanguage defines parameters for SubscribeEvents.
type SubscribeEventsParamsAcceptLanguage string

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = AlertRuleInput

// CreateApprovalMatrixRuleJSONRequestBody defines body for CreateApprovalMatrixRule for application/json ContentType.
type CreateApprovalMatrixRuleJSONRequestBody = ApprovalMatrixRuleWrite

// ApproveApprovalJSONRequestBody defines body for ApproveApproval for application/json ContentType.
type ApproveApprovalJSONRequestBody ApproveApprovalJSONBody

// RejectApprovalJSONRequestBody defines body for RejectApproval for application/json ContentType.
type RejectApprovalJSONRequestBody RejectApprovalJSONBody

// EnrollDeviceJSONRequestBody defines body for EnrollDevice for application/json ContentType.
type EnrollDeviceJSONRequestBody EnrollDeviceJSONBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// CreateAuthSessionJSONRequestBody defines body for CreateAuthSession for application/json ContentType.
type CreateAuthSessionJSONRequestBody CreateAuthSessionJSONBody

// CheckAuthSessionJSONRequestBody defines body for CheckAuthSession for application/json ContentType.
type CheckAuthSessionJSONRequestBody CheckAuthSessionJSONBody

// StepUpJSONRequestBody defines body for StepUp for application/json ContentType.
type StepUpJSONRequestBody StepUpJSONBody

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody IssueTokenJSONBody

// RegisterPushTokenJSONRequestBody defines body for RegisterPushToken for application/json ContentType.
type RegisterPushTokenJSONRequestBody RegisterPushTokenJSONBody

// PutHolidayCalendarJSONRequestBody defines body for PutHolidayCalendar for application/json ContentType.
type PutHolidayCalendarJSONRequestBody = HolidayCalendarWrite

// PutNotificationPreferencesJSONRequestBody defines body for PutNotificationPreferences for application/json ContentType.
type PutNotificationPreferencesJSONRequestBody = NotificationPreferences

// HardClosePeriodJSONRequestBody defines body for HardClosePeriod for application/json ContentType.
type HardClosePeriodJSONRequestBody = PeriodApproval

// OpenAuditAdjustmentPeriodJSONRequestBody defines body for OpenAuditAdjustmentPeriod for application/json ContentType.
type OpenAuditAdjustmentPeriodJSONRequestBody = PeriodApproval

// CreateSodRuleJSONRequestBody defines body for CreateSodRule for application/json ContentType.
type CreateSodRuleJSONRequestBody = SodRuleWrite

// Getter for additional properties for DecisionMeta. Returns the specified
// element and whether it was found
func (a DecisionMeta) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DecisionMeta
func (a *DecisionMeta) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DecisionMeta to handle AdditionalProperties
func (a *DecisionMeta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["as_of"]; found {
		err = json.Unmarshal(raw, &a.AsOf)
		if err != nil {
			return fmt.Errorf("error reading 'as_of': %w", err)
		}
		delete(object, "as_of")
	}

	if raw, found := object["notice"]; found {
		err = json.Unmarshal(raw, &a.Notice)
		if err != nil {
			return fmt.Errorf("error reading 'notice': %w", err)
		}
		delete(object, "notice")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DecisionMeta to handle AdditionalProperties
func (a DecisionMeta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["as_of"], err = json.Marshal(a.AsOf)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'as_of': %w", err)
	}

	if a.Notice != nil {
		object["notice"], err = json.Marshal(a.Notice)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'notice': %w", err)
		}
	}

	object["request_id"], err = json.Marshal(a.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Meta. Returns the specified
// element and whether it was found
func (a Meta) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Meta
func (a *Meta) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Meta to handle AdditionalProperties
func (a *Meta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["as_of"]; found {
		err = json.Unmarshal(raw, &a.AsOf)
		if err != nil {
			return fmt.Errorf("error reading 'as_of': %w", err)
		}
		delete(object, "as_of")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Meta to handle AdditionalProperties
func (a Meta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["as_of"], err = json.Marshal(a.AsOf)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'as_of': %w", err)
	}

	object["request_id"], err = json.Marshal(a.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for PageMeta. Returns the specified
// element and whether it was found
func (a PageMeta) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PageMeta
func (a *PageMeta) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PageMeta to handle AdditionalProperties
func (a *PageMeta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["as_of"]; found {
		err = json.Unmarshal(raw, &a.AsOf)
		if err != nil {
			return fmt.Errorf("error reading 'as_of': %w", err)
		}
		delete(object, "as_of")
	}

	if raw, found := object["next_cursor"]; found {
		err = json.Unmarshal(raw, &a.NextCursor)
		if err != nil {
			return fmt.Errorf("error reading 'next_cursor': %w", err)
		}
		delete(object, "next_cursor")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if raw, found := object["total"]; found {
		err = json.Unmarshal(raw, &a.Total)
		if err != nil {
			return fmt.Errorf("error reading 'total': %w", err)
		}
		delete(object, "total")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PageMeta to handle AdditionalProperties
func (a PageMeta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["as_of"], err = json.Marshal(a.AsOf)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'as_of': %w", err)
	}

	if a.NextCursor != nil {
		object["next_cursor"], err = json.Marshal(a.NextCursor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'next_cursor': %w", err)
		}
	}

	object["request_id"], err = json.Marshal(a.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
	}

	if a.Total != nil {
		object["total"], err = json.Marshal(a.Total)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'total': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
