-- +goose Up
-- Identity tables (P1.2). All mutable: devices, sessions, refresh families, lockouts.
-- Audit of failures goes through erp.audit_events, which is already immutable.
-- None of the tables below are passed to erp.make_immutable.

CREATE TABLE erp.identity_users (
    id               text        PRIMARY KEY,
    login_name       text        NOT NULL UNIQUE,
    display_name     text        NOT NULL,
    company_id       uuid        NOT NULL,
    roles            text[]      NOT NULL DEFAULT '{}',
    personas         text[]      NOT NULL DEFAULT '{}',
    disabled         boolean     NOT NULL DEFAULT false,
    step_up_methods  text[]      NOT NULL DEFAULT '{}',
    created_at       timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE erp.identity_devices (
    id            uuid        PRIMARY KEY,
    user_id       text,
    company_id    uuid,
    public_jwk    jsonb       NOT NULL,
    jkt           text        NOT NULL,
    platform      text        NOT NULL,
    app_version   text        NOT NULL,
    device_name   text        NOT NULL,
    revoked_at    timestamptz,
    created_at    timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX identity_devices_jkt_idx ON erp.identity_devices (jkt);

CREATE TABLE erp.identity_login_sessions (
    id                 uuid        PRIMARY KEY,
    login_name         text        NOT NULL,
    user_id            text,
    company_id         uuid,
    broker_session_id  text        NOT NULL DEFAULT '',
    password_ok        boolean     NOT NULL DEFAULT false,
    second_ok          boolean     NOT NULL DEFAULT false,
    mfa_required       boolean     NOT NULL DEFAULT false,
    shadow             boolean     NOT NULL DEFAULT false,
    expires_at         timestamptz NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE erp.identity_sessions (
    id                 uuid        PRIMARY KEY,
    user_id            text        NOT NULL,
    company_id         uuid        NOT NULL,
    device_id          uuid        NOT NULL REFERENCES erp.identity_devices (id),
    broker_session_id  text        NOT NULL DEFAULT '',
    created_at         timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    ended_at           timestamptz,
    state_version      integer     NOT NULL DEFAULT 1,
    idle_expires_at    timestamptz NOT NULL,
    seq                bigint      GENERATED BY DEFAULT AS IDENTITY
);
CREATE INDEX identity_sessions_user_idx ON erp.identity_sessions (user_id, ended_at, created_at);

CREATE TABLE erp.identity_refresh_tokens (
    id                   uuid        PRIMARY KEY,
    session_id           uuid        NOT NULL REFERENCES erp.identity_sessions (id),
    device_id            uuid        NOT NULL,
    user_id              text        NOT NULL,
    token_hash           text        NOT NULL UNIQUE,
    issued_at            timestamptz NOT NULL,
    expires_at           timestamptz NOT NULL,
    absolute_expires_at  timestamptz NOT NULL,
    used_at              timestamptz,
    revoked_at           timestamptz
);

CREATE TABLE erp.identity_access_tokens (
    jti         text        PRIMARY KEY,
    session_id  uuid        NOT NULL,
    device_id   uuid        NOT NULL,
    user_id     text        NOT NULL,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz
);
CREATE INDEX identity_access_device_idx ON erp.identity_access_tokens (device_id);

CREATE TABLE erp.identity_step_up (
    token_hash  text        PRIMARY KEY,
    user_id     text        NOT NULL,
    session_id  uuid        NOT NULL,
    expires_at  timestamptz NOT NULL,
    used_at     timestamptz
);

CREATE TABLE erp.identity_lockouts (
    login_name    text        PRIMARY KEY,
    failures      integer     NOT NULL DEFAULT 0,
    locked_until  timestamptz
);

CREATE TABLE erp.identity_rate_buckets (
    bucket_key    text        NOT NULL,
    window_start  timestamptz NOT NULL,
    hits          integer     NOT NULL,
    PRIMARY KEY (bucket_key, window_start)
);

CREATE TABLE erp.identity_dpop_jti (
    jti         text        PRIMARY KEY,
    expires_at  timestamptz NOT NULL
);

CREATE TABLE erp.identity_signing_keys (
    kid            text        PRIMARY KEY,
    public_jwk     jsonb       NOT NULL,
    private_pkcs8  bytea       NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
    retired_at     timestamptz
);

-- Rows written inside the request transaction that is rolled back on a failed
-- login, so A2 can show the audit row outliving that transaction.
CREATE TABLE erp.identity_auth_attempts (
    id          uuid        PRIMARY KEY,
    login_name  text        NOT NULL,
    cause       text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);

GRANT SELECT, INSERT, UPDATE ON
    erp.identity_users,
    erp.identity_devices,
    erp.identity_login_sessions,
    erp.identity_sessions,
    erp.identity_refresh_tokens,
    erp.identity_access_tokens,
    erp.identity_step_up,
    erp.identity_lockouts,
    erp.identity_rate_buckets,
    erp.identity_dpop_jti,
    erp.identity_signing_keys,
    erp.identity_auth_attempts
TO erp_app;

-- +goose Down
DROP TABLE IF EXISTS erp.identity_auth_attempts;
DROP TABLE IF EXISTS erp.identity_signing_keys;
DROP TABLE IF EXISTS erp.identity_dpop_jti;
DROP TABLE IF EXISTS erp.identity_rate_buckets;
DROP TABLE IF EXISTS erp.identity_lockouts;
DROP TABLE IF EXISTS erp.identity_step_up;
DROP TABLE IF EXISTS erp.identity_access_tokens;
DROP TABLE IF EXISTS erp.identity_refresh_tokens;
DROP TABLE IF EXISTS erp.identity_sessions;
DROP TABLE IF EXISTS erp.identity_login_sessions;
DROP TABLE IF EXISTS erp.identity_devices;
DROP TABLE IF EXISTS erp.identity_users;
