// Copyright 2022 ZITADEL
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Field numbers and the service name match the Apache-2.0 Session API v2
// shipped in Zitadel v3.4.15 (proto/zitadel/session/v2). Validation, HTTP
// annotations, and unused checks are omitted; they do not affect the wire
// format. The Zitadel server itself is AGPL-3.0 and is not linked (ADR-15).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: session.proto

package zitadelproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ChangeDate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=change_date,json=changeDate,proto3" json:"change_date,omitempty"`
	ResourceOwner string                 `protobuf:"bytes,3,opt,name=resource_owner,json=resourceOwner,proto3" json:"resource_owner,omitempty"`
	CreationDate  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *Details) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Details) GetChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeDate
	}
	return nil
}

func (x *Details) GetResourceOwner() string {
	if x != nil {
		return x.ResourceOwner
	}
	return ""
}

func (x *Details) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        *Checks                `protobuf:"bytes,1,opt,name=checks,proto3" json:"checks,omitempty"`
	Metadata      map[string][]byte      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserAgent     *UserAgent             `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,5,opt,name=lifetime,proto3,oneof" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetChecks() *Checks {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *CreateSessionRequest) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSessionRequest) GetUserAgent() *UserAgent {
	if x != nil {
		return x.UserAgent
	}
	return nil
}

func (x *CreateSessionRequest) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *Details               `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetDetails() *Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type SetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Checks        *Checks                `protobuf:"bytes,3,opt,name=checks,proto3" json:"checks,omitempty"`
	Metadata      map[string][]byte      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,6,opt,name=lifetime,proto3,oneof" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionRequest) Reset() {
	*x = SetSessionRequest{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionRequest) ProtoMessage() {}

func (x *SetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionRequest.ProtoReflect.Descriptor instead.
func (*SetSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *SetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetSessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *SetSessionRequest) GetChecks() *Checks {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *SetSessionRequest) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SetSessionRequest) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

type SetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *Details               `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionResponse) Reset() {
	*x = SetSessionResponse{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionResponse) ProtoMessage() {}

func (x *SetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionResponse.ProtoReflect.Descriptor instead.
func (*SetSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *SetSessionResponse) GetDetails() *Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *SetSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  *string                `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3,oneof" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetSessionToken() string {
	if x != nil && x.SessionToken != nil {
		return *x.SessionToken
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  *string                `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3,oneof" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionRequest) GetSessionToken() string {
	if x != nil && x.SessionToken != nil {
		return *x.SessionToken
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *Details               `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionResponse) GetDetails() *Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type Checks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *CheckUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      *CheckPassword         `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	WebAuthN      *CheckWebAuthN         `protobuf:"bytes,3,opt,name=web_auth_n,json=webAuthN,proto3" json:"web_auth_n,omitempty"`
	Totp          *CheckTOTP             `protobuf:"bytes,5,opt,name=totp,proto3" json:"totp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checks) Reset() {
	*x = Checks{}
	mi := &file_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checks) ProtoMessage() {}

func (x *Checks) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checks.ProtoReflect.Descriptor instead.
func (*Checks) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{9}
}

func (x *Checks) GetUser() *CheckUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Checks) GetPassword() *CheckPassword {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *Checks) GetWebAuthN() *CheckWebAuthN {
	if x != nil {
		return x.WebAuthN
	}
	return nil
}

func (x *Checks) GetTotp() *CheckTOTP {
	if x != nil {
		return x.Totp
	}
	return nil
}

type CheckUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Search:
	//
	//	*CheckUser_UserId
	//	*CheckUser_LoginName
	Search        isCheckUser_Search `protobuf_oneof:"search"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUser) Reset() {
	*x = CheckUser{}
	mi := &file_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUser) ProtoMessage() {}

func (x *CheckUser) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUser.ProtoReflect.Descriptor instead.
func (*CheckUser) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{10}
}

func (x *CheckUser) GetSearch() isCheckUser_Search {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *CheckUser) GetUserId() string {
	if x != nil {
		if x, ok := x.Search.(*CheckUser_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *CheckUser) GetLoginName() string {
	if x != nil {
		if x, ok := x.Search.(*CheckUser_LoginName); ok {
			return x.LoginName
		}
	}
	return ""
}

type isCheckUser_Search interface {
	isCheckUser_Search()
}

type CheckUser_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type CheckUser_LoginName struct {
	LoginName string `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3,oneof"`
}

func (*CheckUser_UserId) isCheckUser_Search() {}

func (*CheckUser_LoginName) isCheckUser_Search() {}

type CheckPassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPassword) Reset() {
	*x = CheckPassword{}
	mi := &file_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPassword) ProtoMessage() {}

func (x *CheckPassword) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPassword.ProtoReflect.Descriptor instead.
func (*CheckPassword) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{11}
}

func (x *CheckPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckWebAuthN struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CredentialAssertionData *structpb.Struct       `protobuf:"bytes,1,opt,name=credential_assertion_data,json=credentialAssertionData,proto3" json:"credential_assertion_data,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CheckWebAuthN) Reset() {
	*x = CheckWebAuthN{}
	mi := &file_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWebAuthN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWebAuthN) ProtoMessage() {}

func (x *CheckWebAuthN) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWebAuthN.ProtoReflect.Descriptor instead.
func (*CheckWebAuthN) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{12}
}

func (x *CheckWebAuthN) GetCredentialAssertionData() *structpb.Struct {
	if x != nil {
		return x.CredentialAssertionData
	}
	return nil
}

type CheckTOTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTOTP) Reset() {
	*x = CheckTOTP{}
	mi := &file_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTOTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTOTP) ProtoMessage() {}

func (x *CheckTOTP) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTOTP.ProtoReflect.Descriptor instead.
func (*CheckTOTP) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{13}
}

func (x *CheckTOTP) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FingerprintId *string                `protobuf:"bytes,1,opt,name=fingerprint_id,json=fingerprintId,proto3,oneof" json:"fingerprint_id,omitempty"`
	Ip            *string                `protobuf:"bytes,2,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAgent) Reset() {
	*x = UserAgent{}
	mi := &file_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAgent) ProtoMessage() {}

func (x *UserAgent) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAgent.ProtoReflect.Descriptor instead.
func (*UserAgent) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{14}
}

func (x *UserAgent) GetFingerprintId() string {
	if x != nil && x.FingerprintId != nil {
		return *x.FingerprintId
	}
	return ""
}

func (x *UserAgent) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *UserAgent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreationDate   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ChangeDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=change_date,json=changeDate,proto3" json:"change_date,omitempty"`
	Sequence       uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Factors        *Factors               `protobuf:"bytes,5,opt,name=factors,proto3" json:"factors,omitempty"`
	Metadata       map[string][]byte      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{15}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Session) GetChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeDate
	}
	return nil
}

func (x *Session) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Session) GetFactors() *Factors {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *Session) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Session) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

type Factors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserFactor            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      *PasswordFactor        `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	WebAuthN      *WebAuthNFactor        `protobuf:"bytes,3,opt,name=web_auth_n,json=webAuthN,proto3" json:"web_auth_n,omitempty"`
	Totp          *TOTPFactor            `protobuf:"bytes,5,opt,name=totp,proto3" json:"totp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factors) Reset() {
	*x = Factors{}
	mi := &file_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factors) ProtoMessage() {}

func (x *Factors) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factors.ProtoReflect.Descriptor instead.
func (*Factors) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{16}
}

func (x *Factors) GetUser() *UserFactor {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Factors) GetPassword() *PasswordFactor {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *Factors) GetWebAuthN() *WebAuthNFactor {
	if x != nil {
		return x.WebAuthN
	}
	return nil
}

func (x *Factors) GetTotp() *TOTPFactor {
	if x != nil {
		return x.Totp
	}
	return nil
}

type UserFactor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerifiedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	LoginName      string                 `protobuf:"bytes,3,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserFactor) Reset() {
	*x = UserFactor{}
	mi := &file_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFactor) ProtoMessage() {}

func (x *UserFactor) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFactor.ProtoReflect.Descriptor instead.
func (*UserFactor) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{17}
}

func (x *UserFactor) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *UserFactor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserFactor) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *UserFactor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserFactor) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type PasswordFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordFactor) Reset() {
	*x = PasswordFactor{}
	mi := &file_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordFactor) ProtoMessage() {}

func (x *PasswordFactor) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordFactor.ProtoReflect.Descriptor instead.
func (*PasswordFactor) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{18}
}

func (x *PasswordFactor) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

type WebAuthNFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	UserVerified  bool                   `protobuf:"varint,2,opt,name=user_verified,json=userVerified,proto3" json:"user_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthNFactor) Reset() {
	*x = WebAuthNFactor{}
	mi := &file_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthNFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthNFactor) ProtoMessage() {}

func (x *WebAuthNFactor) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthNFactor.ProtoReflect.Descriptor instead.
func (*WebAuthNFactor) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{19}
}

func (x *WebAuthNFactor) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *WebAuthNFactor) GetUserVerified() bool {
	if x != nil {
		return x.UserVerified
	}
	return false
}

type TOTPFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPFactor) Reset() {
	*x = TOTPFactor{}
	mi := &file_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPFactor) ProtoMessage() {}

func (x *TOTPFactor) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPFactor.ProtoReflect.Descriptor instead.
func (*TOTPFactor) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{20}
}

func (x *TOTPFactor) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\x12zitadel.session.v2\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\aDetails\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12;\n" +
	"\vchange_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeDate\x12%\n" +
	"\x0eresource_owner\x18\x03 \x01(\tR\rresourceOwner\x12?\n" +
	"\rcreation_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\"\xe2\x02\n" +
	"\x14CreateSessionRequest\x122\n" +
	"\x06checks\x18\x01 \x01(\v2\x1a.zitadel.session.v2.ChecksR\x06checks\x12R\n" +
	"\bmetadata\x18\x02 \x03(\v26.zitadel.session.v2.CreateSessionRequest.MetadataEntryR\bmetadata\x12<\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\v2\x1d.zitadel.session.v2.UserAgentR\tuserAgent\x12:\n" +
	"\blifetime\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x00R\blifetime\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\v\n" +
	"\t_lifetime\"\x92\x01\n" +
	"\x15CreateSessionResponse\x125\n" +
	"\adetails\x18\x01 \x01(\v2\x1b.zitadel.session.v2.DetailsR\adetails\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"\xe2\x02\n" +
	"\x11SetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x122\n" +
	"\x06checks\x18\x03 \x01(\v2\x1a.zitadel.session.v2.ChecksR\x06checks\x12O\n" +
	"\bmetadata\x18\x04 \x03(\v23.zitadel.session.v2.SetSessionRequest.MetadataEntryR\bmetadata\x12:\n" +
	"\blifetime\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x00R\blifetime\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\v\n" +
	"\t_lifetime\"p\n" +
	"\x12SetSessionResponse\x125\n" +
	"\adetails\x18\x01 \x01(\v2\x1b.zitadel.session.v2.DetailsR\adetails\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"n\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\rsession_token\x18\x02 \x01(\tH\x00R\fsessionToken\x88\x01\x01B\x10\n" +
	"\x0e_session_token\"K\n" +
	"\x12GetSessionResponse\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.zitadel.session.v2.SessionR\asession\"q\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\rsession_token\x18\x02 \x01(\tH\x00R\fsessionToken\x88\x01\x01B\x10\n" +
	"\x0e_session_token\"N\n" +
	"\x15DeleteSessionResponse\x125\n" +
	"\adetails\x18\x01 \x01(\v2\x1b.zitadel.session.v2.DetailsR\adetails\"\xee\x01\n" +
	"\x06Checks\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.zitadel.session.v2.CheckUserR\x04user\x12=\n" +
	"\bpassword\x18\x02 \x01(\v2!.zitadel.session.v2.CheckPasswordR\bpassword\x12?\n" +
	"\n" +
	"web_auth_n\x18\x03 \x01(\v2!.zitadel.session.v2.CheckWebAuthNR\bwebAuthN\x121\n" +
	"\x04totp\x18\x05 \x01(\v2\x1d.zitadel.session.v2.CheckTOTPR\x04totp\"Q\n" +
	"\tCheckUser\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x12\x1f\n" +
	"\n" +
	"login_name\x18\x02 \x01(\tH\x00R\tloginNameB\b\n" +
	"\x06search\"+\n" +
	"\rCheckPassword\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"d\n" +
	"\rCheckWebAuthN\x12S\n" +
	"\x19credential_assertion_data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x17credentialAssertionData\"\x1f\n" +
	"\tCheckTOTP\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x9d\x01\n" +
	"\tUserAgent\x12*\n" +
	"\x0efingerprint_id\x18\x01 \x01(\tH\x00R\rfingerprintId\x88\x01\x01\x12\x13\n" +
	"\x02ip\x18\x02 \x01(\tH\x01R\x02ip\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01B\x11\n" +
	"\x0f_fingerprint_idB\x05\n" +
	"\x03_ipB\x0e\n" +
	"\f_description\"\xcc\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12;\n" +
	"\vchange_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeDate\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x125\n" +
	"\afactors\x18\x05 \x01(\v2\x1b.zitadel.session.v2.FactorsR\afactors\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).zitadel.session.v2.Session.MetadataEntryR\bmetadata\x12H\n" +
	"\x0fexpiration_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0eexpirationDate\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x12\n" +
	"\x10_expiration_date\"\xf3\x01\n" +
	"\aFactors\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.zitadel.session.v2.UserFactorR\x04user\x12>\n" +
	"\bpassword\x18\x02 \x01(\v2\".zitadel.session.v2.PasswordFactorR\bpassword\x12@\n" +
	"\n" +
	"web_auth_n\x18\x03 \x01(\v2\".zitadel.session.v2.WebAuthNFactorR\bwebAuthN\x122\n" +
	"\x04totp\x18\x05 \x01(\v2\x1e.zitadel.session.v2.TOTPFactorR\x04totp\"\xc4\x01\n" +
	"\n" +
	"UserFactor\x12;\n" +
	"\vverified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"login_name\x18\x03 \x01(\tR\tloginName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\"M\n" +
	"\x0ePasswordFactor\x12;\n" +
	"\vverified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\"r\n" +
	"\x0eWebAuthNFactor\x12;\n" +
	"\vverified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12#\n" +
	"\ruser_verified\x18\x02 \x01(\bR\fuserVerified\"I\n" +
	"\n" +
	"TOTPFactor\x12;\n" +
	"\vverified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt2\x96\x03\n" +
	"\x0eSessionService\x12d\n" +
	"\rCreateSession\x12(.zitadel.session.v2.CreateSessionRequest\x1a).zitadel.session.v2.CreateSessionResponse\x12[\n" +
	"\n" +
	"SetSession\x12%.zitadel.session.v2.SetSessionRequest\x1a&.zitadel.session.v2.SetSessionResponse\x12[\n" +
	"\n" +
	"GetSession\x12%.zitadel.session.v2.GetSessionRequest\x1a&.zitadel.session.v2.GetSessionResponse\x12d\n" +
	"\rDeleteSession\x12(.zitadel.session.v2.DeleteSessionRequest\x1a).zitadel.session.v2.DeleteSessionResponseBHZFgithub.com/jaichahal/smart-erp/apps/api/internal/identity/zitadelprotob\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_session_proto_goTypes = []any{
	(*Details)(nil),               // 0: zitadel.session.v2.Details
	(*CreateSessionRequest)(nil),  // 1: zitadel.session.v2.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 2: zitadel.session.v2.CreateSessionResponse
	(*SetSessionRequest)(nil),     // 3: zitadel.session.v2.SetSessionRequest
	(*SetSessionResponse)(nil),    // 4: zitadel.session.v2.SetSessionResponse
	(*GetSessionRequest)(nil),     // 5: zitadel.session.v2.GetSessionRequest
	(*GetSessionResponse)(nil),    // 6: zitadel.session.v2.GetSessionResponse
	(*DeleteSessionRequest)(nil),  // 7: zitadel.session.v2.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 8: zitadel.session.v2.DeleteSessionResponse
	(*Checks)(nil),                // 9: zitadel.session.v2.Checks
	(*CheckUser)(nil),             // 10: zitadel.session.v2.CheckUser
	(*CheckPassword)(nil),         // 11: zitadel.session.v2.CheckPassword
	(*CheckWebAuthN)(nil),         // 12: zitadel.session.v2.CheckWebAuthN
	(*CheckTOTP)(nil),             // 13: zitadel.session.v2.CheckTOTP
	(*UserAgent)(nil),             // 14: zitadel.session.v2.UserAgent
	(*Session)(nil),               // 15: zitadel.session.v2.Session
	(*Factors)(nil),               // 16: zitadel.session.v2.Factors
	(*UserFactor)(nil),            // 17: zitadel.session.v2.UserFactor
	(*PasswordFactor)(nil),        // 18: zitadel.session.v2.PasswordFactor
	(*WebAuthNFactor)(nil),        // 19: zitadel.session.v2.WebAuthNFactor
	(*TOTPFactor)(nil),            // 20: zitadel.session.v2.TOTPFactor
	nil,                           // 21: zitadel.session.v2.CreateSessionRequest.MetadataEntry
	nil,                           // 22: zitadel.session.v2.SetSessionRequest.MetadataEntry
	nil,                           // 23: zitadel.session.v2.Session.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 25: google.protobuf.Duration
	(*structpb.Struct)(nil),       // 26: google.protobuf.Struct
}
var file_session_proto_depIdxs = []int32{
	24, // 0: zitadel.session.v2.Details.change_date:type_name -> google.protobuf.Timestamp
	24, // 1: zitadel.session.v2.Details.creation_date:type_name -> google.protobuf.Timestamp
	9,  // 2: zitadel.session.v2.CreateSessionRequest.checks:type_name -> zitadel.session.v2.Checks
	21, // 3: zitadel.session.v2.CreateSessionRequest.metadata:type_name -> zitadel.session.v2.CreateSessionRequest.MetadataEntry
	14, // 4: zitadel.session.v2.CreateSessionRequest.user_agent:type_name -> zitadel.session.v2.UserAgent
	25, // 5: zitadel.session.v2.CreateSessionRequest.lifetime:type_name -> google.protobuf.Duration
	0,  // 6: zitadel.session.v2.CreateSessionResponse.details:type_name -> zitadel.session.v2.Details
	9,  // 7: zitadel.session.v2.SetSessionRequest.checks:type_name -> zitadel.session.v2.Checks
	22, // 8: zitadel.session.v2.SetSessionRequest.metadata:type_name -> zitadel.session.v2.SetSessionRequest.MetadataEntry
	25, // 9: zitadel.session.v2.SetSessionRequest.lifetime:type_name -> google.protobuf.Duration
	0,  // 10: zitadel.session.v2.SetSessionResponse.details:type_name -> zitadel.session.v2.Details
	15, // 11: zitadel.session.v2.GetSessionResponse.session:type_name -> zitadel.session.v2.Session
	0,  // 12: zitadel.session.v2.DeleteSessionResponse.details:type_name -> zitadel.session.v2.Details
	10, // 13: zitadel.session.v2.Checks.user:type_name -> zitadel.session.v2.CheckUser
	11, // 14: zitadel.session.v2.Checks.password:type_name -> zitadel.session.v2.CheckPassword
	12, // 15: zitadel.session.v2.Checks.web_auth_n:type_name -> zitadel.session.v2.CheckWebAuthN
	13, // 16: zitadel.session.v2.Checks.totp:type_name -> zitadel.session.v2.CheckTOTP
	26, // 17: zitadel.session.v2.CheckWebAuthN.credential_assertion_data:type_name -> google.protobuf.Struct
	24, // 18: zitadel.session.v2.Session.creation_date:type_name -> google.protobuf.Timestamp
	24, // 19: zitadel.session.v2.Session.change_date:type_name -> google.protobuf.Timestamp
	16, // 20: zitadel.session.v2.Session.factors:type_name -> zitadel.session.v2.Factors
	23, // 21: zitadel.session.v2.Session.metadata:type_name -> zitadel.session.v2.Session.MetadataEntry
	24, // 22: zitadel.session.v2.Session.expiration_date:type_name -> google.protobuf.Timestamp
	17, // 23: zitadel.session.v2.Factors.user:type_name -> zitadel.session.v2.UserFactor
	18, // 24: zitadel.session.v2.Factors.password:type_name -> zitadel.session.v2.PasswordFactor
	19, // 25: zitadel.session.v2.Factors.web_auth_n:type_name -> zitadel.session.v2.WebAuthNFactor
	20, // 26: zitadel.session.v2.Factors.totp:type_name -> zitadel.session.v2.TOTPFactor
	24, // 27: zitadel.session.v2.UserFactor.verified_at:type_name -> google.protobuf.Timestamp
	24, // 28: zitadel.session.v2.PasswordFactor.verified_at:type_name -> google.protobuf.Timestamp
	24, // 29: zitadel.session.v2.WebAuthNFactor.verified_at:type_name -> google.protobuf.Timestamp
	24, // 30: zitadel.session.v2.TOTPFactor.verified_at:type_name -> google.protobuf.Timestamp
	1,  // 31: zitadel.session.v2.SessionService.CreateSession:input_type -> zitadel.session.v2.CreateSessionRequest
	3,  // 32: zitadel.session.v2.SessionService.SetSession:input_type -> zitadel.session.v2.SetSessionRequest
	5,  // 33: zitadel.session.v2.SessionService.GetSession:input_type -> zitadel.session.v2.GetSessionRequest
	7,  // 34: zitadel.session.v2.SessionService.DeleteSession:input_type -> zitadel.session.v2.DeleteSessionRequest
	2,  // 35: zitadel.session.v2.SessionService.CreateSession:output_type -> zitadel.session.v2.CreateSessionResponse
	4,  // 36: zitadel.session.v2.SessionService.SetSession:output_type -> zitadel.session.v2.SetSessionResponse
	6,  // 37: zitadel.session.v2.SessionService.GetSession:output_type -> zitadel.session.v2.GetSessionResponse
	8,  // 38: zitadel.session.v2.SessionService.DeleteSession:output_type -> zitadel.session.v2.DeleteSessionResponse
	35, // [35:39] is the sub-list for method output_type
	31, // [31:35] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_session_proto_msgTypes[1].OneofWrappers = []any{}
	file_session_proto_msgTypes[3].OneofWrappers = []any{}
	file_session_proto_msgTypes[5].OneofWrappers = []any{}
	file_session_proto_msgTypes[7].OneofWrappers = []any{}
	file_session_proto_msgTypes[10].OneofWrappers = []any{
		(*CheckUser_UserId)(nil),
		(*CheckUser_LoginName)(nil),
	}
	file_session_proto_msgTypes[14].OneofWrappers = []any{}
	file_session_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
